### ISSUE TITLE
roslaunch naoqi_driver naoqi_driver.launch nao_ip:=<ROBOT_IP> returns an error

### ISSUE THREAD

**Issue by ravitchad** [nlyubova/tutorials-for-Nao-Pepper-Romeo#1]
Hello, 

I want to connect Nao to ROS and was following your tutorial(https://github.com/nlyubova/tutorials-for-Nao-Pepper-Romeo/blob/master/distr/tuto_kinetic.rst) where I encountered an error when I run the following command: 

roslaunch naoqi_driver naoqi_driver.launch nao_ip:=169.254.88.3

... logging to /home/ravi/.ros/log/13d12000-0ff7-11e8-84c1-cc3d82563088/roslaunch-ravi-laptop-16894.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ravi-laptop:40427/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /
    naoqi_driver (naoqi_driver/naoqi_driver_node)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
/opt/ros/kinetic/lib/naoqi_driver/naoqi_driver_node: error while loading shared libraries: libopencv_core3.so.3.3: cannot open shared object file: No such file or directory
process[naoqi_driver-1]: started with pid [16912]
================================================================================REQUIRED process [naoqi_driver-1] has died!
process has died [pid 16912, exit code 127, cmd /opt/ros/kinetic/lib/naoqi_driver/naoqi_driver_node --qi-url=tcp://169.254.88.3:9559 --roscore_ip=127.0.0.1 --network_interface=eth0 __name:=naoqi_driver __log:=/home/ravi/.ros/log/13d12000-0ff7-11e8-84c1-cc3d82563088/naoqi_driver-1.log].
log file: /home/ravi/.ros/log/13d12000-0ff7-11e8-84c1-cc3d82563088/naoqi_driver-1*.log
Initiating shutdown!
================================================================================
[naoqi_driver-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Please let me know what I can do to fix this issue. Thanks in advance!

**Comment by nlyubova** [comment]
The issue is related to your Naoqi_driver installation and opencv. How did you install naoqi driver ? With apt-get or from source? Try with apt-get

Which versions of opencv do you have installed?

**Comment by nlyubova** [comment]
Please follow the official tutorials as I want to remove this one

**Comment by ravitchad** [comment]
Thanks for your quick reply.

I installed the naoqi_driver using apt-get -- "sudo apt-get install ros-kinetic-naoqi-driver"

opencv version: 3.2.0-dev

By official tutorials do you mean this: http://ros-naoqi.github.io/naoqi_driver/ --> if not, please give me a link, thanks.

**Comment by nlyubova** [comment]
For all official tutorials, check this pages:
 - http://ros-naoqi.github.io/naoqi_driver/
 - http://wiki.ros.org/pepper
 - http://wiki.ros.org/nao
